services:
  - mysql
before_script:
  - mysql -e 'create database connection_test;'
  - travis_retry composer self-update
  - composer install --dev
language: php
php:
  - 5.5
  - 5.6
  - 7.0
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/coveralls -v