services:
  - mysql
before_script:
  - mysql -e 'create database connection_test;'
  - travis_retry composer self-update
  - composer install --dev
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
script:
  - ./vendor/bin/phpunit