services:
  - mysql
before_script:
  - mysql -e 'create database connection_test;'
  - travis_retry composer self-update
  - composer install --dev
language: php
php:
  - 5.5
  - 5.6
  - 7.0
script:
  - ./vendor/bin/phpunit
addons:
    code_climate:
        repo_token: 026c5d9d15ca3c41944a1f8b8527adc3e43d723a6b7fa8a693be7ed75758e0f8